version: "3.8"

services:
  mongo:
    container_name: poll_api_mongo
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: poll_api_container
    build: .
    image: poll_api
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/src/poll_api/dist
    ports:
      - "5050:5050"
    depends_on:
      - mongo