version: "3.8"

services:
  mongo:
    container_name: poll_api_mongo
    image: mongo:3.7
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_DATABASE=poll_api
    networks:
      - app-network

  api:
    container_name: poll_api_container
    build: .
    image: node:20
    working_dir: /usr/src/poll_api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist:/usr/src/poll_api/dist
      - ./package.json:/usr/src/poll_api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    environment:
      - MONGO_URL=mongodb://mongo:27017/poll_api
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
